### ISSUE TITLE
Typescript definitions wrong with 21.2.6

### ISSUE THREAD

**Issue by Delagen** [jackocnr/intl-tel-input#1590]
### Steps to reproduce
1.  Compile TS with libCheck

### Expected behaviour
Success

### Actual behaviour
Error: node_modules/intl-tel-input/build/js/intlTelInput.d.ts:545:37 - error TS2307: Cannot find module 'i18n/en/countries.mjs' or its corresponding type declarations.
545     import countryTranslations from "i18n/en/countries.mjs";
                                        ~~~~~~~~~~~~~~~~~~~~~~~
Error: node_modules/intl-tel-input/build/js/intlTelInput.d.ts:546:39 - error TS2307: Cannot find module 'i18n/en/interface.mjs' or its corresponding type declarations.
546     import interfaceTranslations from "i18n/en/interface.mjs";
                                          ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jackocnr** [comment]
Thanks for reporting this. Can you confirm that it works fine in the previous version: v21.2.5?

**Comment by Delagen** [comment]
@jackocnr Yes. I temporary reverted to this version.

**Comment by jackocnr** [comment]
Thanks. @anthony0030 this error must be a result of the translation export changes we made - is there any chance you could take a look at this?

**Comment by anthony0030** [comment]
Hi @jackocnr, I don’t have any experience really with TS. I would love to help but don’t know how.

**Comment by jackocnr** [comment]
No worries, I'll take a look when I find some time.

**Comment by MarcoGlauser** [comment]
Just another datapoint. Our CI build broke when trying to update to the newest version this morning. Fixing the library to 21.2.5 resolved the issue in the short tem.
Thank you for supporting this package for such a long time!

**Comment by jackocnr** [comment]
@Delagen I've implemented the fix I mentioned [here](https://github.com/jackocnr/intl-tel-input/issues/1590#issuecomment-2080539072), and released it as v21.2.8 - can you give that a try and see if that fixes your issue?

**Comment by Delagen** [comment]
> @Delagen I've implemented the fix I mentioned [here](https://github.com/jackocnr/intl-tel-input/issues/1590#issuecomment-2080539072), and released it as v21.2.8 - can you give that a try and see if that fixes your issue?

Seems it works now. Thanks.
