### ISSUE TITLE
Uncaught TypeError: $(...).intlTelInput is not a function after upgraded to jquery 3.1.1

### ISSUE THREAD

**Issue by anupamadhuri** [jackocnr/intl-tel-input#774]
Uncaught TypeError: $(...).intlTelInput is not a function

Issue is coming after jquery upgrade. 
For older version jquery jquery-1.11.3 it was working fine.
For upgraded version jquery-3.1.1 it is not working
### Steps to reproduce
I have included css and js
<link rel="stylesheet" type="text/css" href="/stylesheets/intlTelInput.css">
<script type="text/javascript" src="/javascript/intlTelInput.js"></script>

at the end of page
<script>
    $(document).ready(function() {
$( document ).ready(function() {
        $('#PhoneCountryCode').intlTelInput();
        $('.flag-dropdown').click(function() {
            addDialCodeExt();
        })
    });

    function addDialCodeExt() {
        if ($('#PhoneCountryCode').val().indexOf('+') < 0) {
            $('#PhoneCountryCode').val("+");
        }
    }
    });
</script>

**Comment by jackocnr** [comment]
Please make sure you are loading jquery first, then the plugin script, and only initialising the plugin after that. If you're still having a problem, then if you can reproduce the issue in a codepen (stripping down the code to the simplest possible form that reproduces the error), then I'd be happy to take a look.

**Comment by anupamadhuri** [comment]
Thanks.
Jquery is loading first and then plugin script.
We are migrating jquery to 3.1.1
It was working fine on earlier version. After upgrade it is not working.

**Comment by anupamadhuri** [comment]
Fixed
Solution:
In intlTelInput.js replace
.load(function() { ... });
To
.on('load', function() { ... });

**Comment by jackocnr** [comment]
We don't use `.load` anywhere in the plugin code. Please make sure you're using the latest version.

**Comment by anupamadhuri** [comment]
Ohk might be its old version

**Comment by anupamadhuri** [comment]
May I know which is the stable version which can be worked with jquery 3.3.1

**Comment by jackocnr** [comment]
Best version to use is the latest one, so currently that's v13.0.2.

**Comment by anupamadhuri** [comment]
Hi,

Sorry I am asking you very minor issues but I need to fix this very urgent.
I am not able to see icons for country code
Please refer
http://nimb.ws/ohjytC

**Comment by shreyanshpanchal** [comment]
I'm facing same issue, 
Im using Laravel Mix to get jQuery & intl-tel-input.js to minified.
And im sure im using this intlTelnput way down in the body after all the scripts are downloaded. 


I get this same error.

**Comment by brada1703** [comment]
I had the same issue. 

Note that:

**IMPORTANT: since v14 we have removed the jQuery dependency. See below for how to initialise and use the plugin with pure JavaScript. If you want to stick with the jQuery version, there is now a separate jQuery wrapped version.**

This is why my previous code was breaking.

Previously, I used:

$("#input-phone").intlTelInput({
    formatOnDisplay: false,
    nationalMode: false,
    autoPlaceholder: 'aggressive',
    separateDialCode: true,
    preferredCountries: ['BE', 'GB'],
});

Now, I must use:

        var input = document.querySelector("#input-phone");
        window.intlTelInput(input);

I hope this helps someone.

**Comment by vishalsanwar** [comment]
Hi 

When I tried to pass dynamic countries (Ajax response) into the onlyCountries. it gives me below error.
intlTelInput.js:227 Uncaught TypeError: this.options.onlyCountries.map is not a function
Please help me to fix this .

for more info : I got the categories ['in','us'] in the response when I pass hard coded then it's work but not working with Ajax response. I also put that script on the time out function, still no luck.

Thanks

**Comment by PwntasticKev** [comment]
@shreyanshpanchal Did you end up finding your issue?

**Comment by nichalko** [comment]
I will leave what worked for me - laravel mix setup: 

`
// vendors
import intlTelInput from "intl-tel-input";
import telUtils from "../../../node_modules/intl-tel-input/build/js/utils";

var input = document.querySelector("#phone");

var iti = intlTelInput(input, {
    utlisScript: telUtils
});

iti.promise.then(function () {
    console.log("Initialised!")
})
`

or use without the promise:

`
// vendors
import intlTelInput from "intl-tel-input";
import telUtils from "../../../node_modules/intl-tel-input/build/js/utils";

var input = document.querySelector("#phone");

var iti = intlTelInput(input, {
    utlisScript: telUtils
});

`

CSS is imported as 
`
@import "../../../node_modules/intl-tel-input/build/css/intlTelInput.css";
`

BTW: nice packet but the docs are blurry...

**Comment by Anujndls** [comment]
I am still facing the issue, jquery version 2.2.4.
Please help!

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by simioluwatomi** [comment]
> I will leave what worked for me - laravel mix setup:
> 
> ```
> // one of my js module files: //
> 
> import intlTelInput from "intl-tel-input";
> import telUtils from "../../../node_modules/intl-tel-input/build/js/utils";
> 
> var input = document.querySelector("#phone");
> 
> var iti = intlTelInput(input, {
>     utlisScript: telUtils
> });
> 
> iti.promise.then(function () {
>     console.log("Initialised!")
> })
> ```
> 
> or use without the promise:
> 
> ```
> // in one of my js module files: //
> 
> import intlTelInput from "intl-tel-input";
> import telUtils from "../../../node_modules/intl-tel-input/build/js/utils";
> 
> var input = document.querySelector("#phone");
> 
> var iti = intlTelInput(input, {
>     utlisScript: telUtils
> });
> ```
> 
> CSS is imported as
> 
> ```
> @import "../../../node_modules/intl-tel-input/build/css/intlTelInput.css";
> ```
> 
> BTW: nice packet but the docs are blurry...

Just set this up now but had to change some things

```
import intlTelInput from "intl-tel-input";
import telUtils from "intl-tel-input/build/js/utils";

var input = document.querySelector("#phone");

var iti = intlTelInput(input, {
    utlisScript: telUtils
});

iti.promise.then(function () {
    console.log("Initialised!")
})
```

```
// import tel input css in sass file
@import "~intl-tel-input/build/css/intlTelInput.css";
```

The ~ is an alias to the `node_modules` folder. Thanks for your comment too.

**Comment by garrettvorce** [comment]
> I will leave what worked for me - laravel mix setup:
> 
> ```
> // one of my js module files: //
> 
> import intlTelInput from "intl-tel-input";
> import telUtils from "../../../node_modules/intl-tel-input/build/js/utils";
> 
> var input = document.querySelector("#phone");
> 
> var iti = intlTelInput(input, {
>     utlisScript: telUtils
> });
> 
> iti.promise.then(function () {
>     console.log("Initialised!")
> })
> ```
> 
> or use without the promise:
> 
> ```
> // in one of my js module files: //
> 
> import intlTelInput from "intl-tel-input";
> import telUtils from "../../../node_modules/intl-tel-input/build/js/utils";
> 
> var input = document.querySelector("#phone");
> 
> var iti = intlTelInput(input, {
>     utlisScript: telUtils
> });
> ```
> 
> CSS is imported as
> 
> ```
> @import "../../../node_modules/intl-tel-input/build/css/intlTelInput.css";
> ```
> 
> BTW: nice packet but the docs are blurry...

Confirmed working with Laravel 6.0 -- thanks for your help man!

**Comment by jamshidhashimi** [comment]
I had the same problem, and I resolved it by using this package: https://github.com/EducationLink/vue-tel-input

**Comment by davidjackson148** [comment]
> I had the same issue.
> 
> Note that:
> 
> **IMPORTANT: since v14 we have removed the jQuery dependency. See below for how to initialise and use the plugin with pure JavaScript. If you want to stick with the jQuery version, there is now a separate jQuery wrapped version.**
> 
> This is why my previous code was breaking.
> 
> Previously, I used:
> 
> ```
> $("#input-phone").intlTelInput({
>     formatOnDisplay: false,
>     nationalMode: false,
>     autoPlaceholder: 'aggressive',
>     separateDialCode: true,
>     preferredCountries: ['BE', 'GB'],
> });
> ```
> 
> Now, I must use:
> 
> ```
>         var input = document.querySelector("#input-phone");
>         window.intlTelInput(input);
> ```
> 
> I hope this helps someone.

This works but there is no way to get the country selected code ? How would I do this please

**Comment by davidjackson148** [comment]
using this syntax `$("#input-phone").intlTelInput({...` the field formats correctly but there seems no way to retried the selected country code
