### ISSUE TITLE
Error in Mozilla Firefox.

### ISSUE THREAD

**Issue by narasimhakamath** [jackocnr/intl-tel-input#900]
When I was using v.12.4.0, it seemed to be working without any issues in both Google Chrome and Mozilla Firefox.

When I updated the library to 15.0, it still works fine in Chrome but in Mozilla, I get the following errors.

SyntaxError: invalid range in character class
TypeError: telInputNew.intlTelInput is not a function

I'm using jQuery v3.3.1.

**Comment by narasimhakamath** [comment]
Screenshot in Chrome and Firefox respectively.

![CHROME](https://user-images.githubusercontent.com/38852388/58403095-7eea5880-807f-11e9-9f8b-6d61f3370ff9.png)

![FIREFOX](https://user-images.githubusercontent.com/38852388/58403127-8c074780-807f-11e9-8226-740584c869f6.png)

**Comment by jackocnr** [comment]
See notice at top of readme.

**Comment by narasimhakamath** [comment]
I'm sorry, but please enlighten me on why it works on Chrome but not on Firefox.

And the information is unclear.

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by zh0014in** [comment]
i just had this problem too, adding 'charset="UTF-8"' to the intl-tel-input script tag solved it.

**Comment by dipanjal** [comment]
> i just had this problem too, adding 'charset="UTF-8"' to the intl-tel-input script tag solved it.

saved my day
thank you so much
